---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: 10-allow-api-to-db
  namespace: phippy
spec:
  podSelector:
    matchLabels:
        app.kubernetes.io/name: phippy
        app.kubernetes.io/component: db
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: phippy
              app.kubernetes.io/component: api
      ports:
        - protocol: TCP
          port: 6379
