---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: 20-allow-ui-to-api
  namespace: phippy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: phippy
      app.kubernetes.io/component: api
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: phippy
              app.kubernetes.io/component: ui
      ports:
        - protocol: TCP
          port: 5000
