version: "3.7"

services: 
  ui:
    image: phippy-ui:v1.0
    environment:
      # API_HOST: api
      # API_PORT: 5000
      API_HOST: host.docker.internal
      API_PORT: 8000
    ports:
      - "8080:5000"
    networks:
      - phippy-net
    depends_on:
      - api
  api:
    image: phippy-api:v1.0
    environment:
      # DB_HOST: redis
      DB_HOST: host.docker.internal
      DB_PORT: 6379
    ports:
      - "8081:5000"
    networks:
      - phippy-net
    depends_on:
      - redis
  redis:
    image: ghcr.io/hlesey/redis:7.4
    networks:
      - phippy-net
    ports:
      - "6379:6379"
  redis-exporter:
    image: ghcr.io/hlesey/bitnami/redis-exporter:1.62.0
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "9121:9121"
    networks:
      - phippy-net
networks:
  phippy-net:
    name: phippy-net
