version: "3.7"

services: 
  ui:
    image: ghcr.io/hlesey/phippy-ui:1.0
    environment:
      API_HOST: api
      API_PORT: 5000
    ports:
      - "8080:5000"
    networks:
      - phippy-net
    depends_on:
      - api
  api:
    image: ghcr.io/hlesey/phippy-api:1.0
    environment:
      DB_HOST: redis
      DB_PORT: 6379
    ports:
      - "5000:5000"
    networks:
      - phippy-net
    depends_on:
      - redis
  redis:
    image: ghcr.io/hlesey/redis:6.2.6
    networks:
      - phippy-net
  redis-exporter:
    image: bitnami/redis-exporter:1.36.0
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "9121:9121"
    networks:
      - phippy-net
networks:
  phippy-net:
    name: phippy-net
