version: "3.7"

services: 
  ui:
    image: ghcr.io/hlesey/phippy-ui:1.0
    environment:
      API_HOST: api
      API_PORT: 5000
      FLASK_ENV: development
    ports:
      - "8080:5000"
    networks:
      - phippy-net
    depends_on:
      - api
  api:
    image: ghcr.io/hlesey/phippy-api:1.0
    environment:
      DB_HOST: db
      DB_PORT: 6379
      FLASK_ENV: development
    ports:
      - "5000:5000"
    networks:
      - phippy-net
    depends_on:
      - db
  db:
    image: ghcr.io/hlesey/redis:4
    networks:
      - phippy-net
networks:
  phippy-net:
    name: phippy-net