version: "3.7"

services:
  web:
    image: ghcr.io/hlesey/phippy:1.0
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FLASK_ENV: development
    ports:
      - "5000:5000"
    networks:
      - phippy
    depends_on:
      - redis
  redis:
    image: ghcr.io/hlesey/redis:4
    ports:
      - "6379:6379"
    networks:
      - phippy
networks:
  phippy:
    name: phippy