apiVersion: v1
kind: Service
metadata:
  name: phippy-clusterip
  labels:
    name: phippy
    app: phippy
spec:
  selector:
    app: phippy
  type: ClusterIP
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP