apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: phippy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: phippy.local
    http:
      paths:
      - path: /
        backend:
          serviceName: phippy-clusterip
          servicePort: 80