apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.name" . }}-api
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
    FLASK_ENV: "development"
    REDIS_PORT: "6379"
    REDIS_HOST: {{ include "common.name" . }}-db
