apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.name" . }}-api
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
    DB_PORT: "6379"
    DB_HOST: {{ include "common.name" . }}-db
