apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.name" . }}-ui
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
    API_PORT: "80"
    API_HOST: {{ include "common.name" . }}-api
