apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.name" . }}-ui
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      annotations:
        {{- toYaml .Values.ui.podAnnotations | nindent 8 }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ include "common.name" . }}-ui
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
