apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.name" . }}-ui
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  rules:
  - host: "{{ .Values.ui.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: "Prefix"
        backend:
          service:
            name: {{ include "common.name" . }}-ui
            port:
              name: http
