apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: phippy-deployment
  labels:
    app: phippy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phippy
  template:
    metadata:
      labels:
        app: phippy
    spec:
      containers:
      - name: phippy
        image: trainersontheweb/phippy:latest
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http