apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: phippy-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: phippy-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50