---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: phippy-api-hpa
  namespace: phippy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phippy-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 25
        type: Utilization
    type: Resource
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
