apiVersion: v2
name: phippy
description: A Helm chart for phippy app
type: application
version: 0.1.0
appVersion: "1.0.0"
# dependencies:
#   - name: redis
#     repository: https://charts.bitnami.com/bitnami
#     version: 6.2.6
