
api:
  replicaCount: 2
  image:
    registry: ghcr.io
    repository: hlesey/phippy-api
    tag: "1.0"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  service:
    type: ClusterIP
    port: 80

ui:
  replicaCount: 2
  image:
    registry: ghcr.io
    repository: hlesey/phippy-ui
    tag: "1.0"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 25
    targetMemoryUtilizationPercentage: 25
  service:
    type: ClusterIP
    port: 80
  ingress:
    host: phippy.clusterx.qedzone.ro
